module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "PREFIX": ".",
  "SESSION_ID": "put your session id",
  "AUTO_READ_STATUS": "false",
  "MODE": "private",
  "BOT_NUMBER": "94742274855",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "false",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": false,
  "DELETEMSGSENDTO": "94742274855",
  "ALWAYS_ONLINE": "false",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "OWNER_NUMBER": "94742274855",
  "AUTO_BIO": "false",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
};